# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b1e6eb4005a2f2cbe85350bec975a0e0acd1f27a819672f7e6fc3ce908853e98bfd464217d22d1457fa472b3f441a1147bb0891893ab0ed7fe2a2e0f33a66f

test:
  secret_key_base: 400406cae1faa246bb27d7a789ac9a455ecdf9970aa7f50b44282dca07427ff6e6921a78e2ff46fd549a74a2cb7f088946a6657315fb8e11546f09a13cee5faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
